name: MinecraftServerAPI
version: 1.0
description: Provides RESTful APIs and WebHooks for managing and automating your Minecraft server.
website: https://github.com/Shweit/MinecraftServerAPI
author: Shweit
contributors:
  - Shweit
api-version: 1.21
softdepend:
  - Maintenance

main: com.shweit.serverapi.MinecraftServerAPI

commands:
  webhooks:
    description: Command to manage the Webhooks.
    usage: /webhooks <command> [args]
    permission: mcapi.webhooks
    aliases:
      - wh