name: MinecraftServerAPI
version: 1.0
description: A plugin that allows you to interact with your Minecraft server using a REST API.
author: Shweit
api-version: 1.21
softdepend:
  - Maintenance


main: com.shweit.serverapi.MinecraftServerAPI

commands:
  webhooks:
    description: Command to manage the Webhooks.
    usage: /webhooks <command> [args]
    permission: mcapi.webhooks
    aliases:
      - wh