name: Maven Release

'on':
  release:
    types: [published]

jobs:
  publish:
    name: Build and Upload JARs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Make sure to set the correct Java version for your project
          distribution: temurin

      - name: Set maven project version
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build and package Maven project
        run: mvn clean package -DskipTests

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/MinecraftServerAPI-${{ github.event.release.tag_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Modrinth
        run: |
          curl -X POST https://api.modrinth.com/v2/version \
          -H "Authorization: Bearer ${{ secrets.MODRINTH_TOKEN }}" \
          -H "Content-Type: multipart/form-data" \
          -F "data={
              \"name\": \"${{ github.event.release.tag_name }}\",
              \"version_number\": \"${{ github.event.release.tag_name }}\",
              \"changelog\": \"${{ github.event.release.body }}\",
              \"dependencies\": [],
              \"game_versions\": [\"1.16.5\", \"1.17.1\"],
              \"version_type\": \"release\",
              \"loaders\": [\"fabric\", \"forge\", \"spigot\"],
              \"featured\": true,
              \"status\": \"listed\",
              \"requested_status\": \"listed\"
            }" \
          -F "file=@target/MinecraftServerAPI-${{ github.event.release.tag_name }}.jar" \
          -F "file_parts=file" \
          -F "primary_file=file"
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
