name: Runtime Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Maven Build
        run: mvn clean package

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.event.number }}
          path: 'target/MinecraftServerAPI*.jar'

  runtime-test:
    name: Plugin Runtime Test
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '1.8.9'
            javaVersion: '8'
          - mcVersion: '1.9.4'
            javaVersion: '9'
          - mcVersion: '1.10.2'
            javaVersion: '10'
          - mcVersion: '1.11.2'
            javaVersion: '11'
          - mcVersion: '1.12.2'
            javaVersion: '12'
          - mcVersion: '1.13.2'
            javaVersion: '13'
          - mcVersion: '1.14.4'
            javaVersion: '14'
          - mcVersion: '1.15.2'
            javaVersion: '15'
          - mcVersion: '1.16.5'
            javaVersion: '16'
          - mcVersion: '1.17.1'
            javaVersion: '17'
          - mcVersion: '1.18.2'
            javaVersion: '18'
          - mcVersion: '1.19.4'
            javaVersion: '19'
          - mcVersion: '1.20.1'
            javaVersion: '20'
          - mcVersion: '1.21'
            javaVersion: '21'

    steps:
      - uses: FN-FAL113/minecraft-plugin-runtime-test@v1.1.2
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: artifact-${{ github.event.number }}