name: Runtime Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ 'paper', 'spigot', 'craftbukkit' ]
        version: [ '1.17', '1.18', '1.19', '1.20', '1.21' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install
      - uses: gmitch215/TestMC@v2
        with:
          path: 'target/MinecraftServerAPI*.jar'
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix.version }}
          time: 120
          commands: |
            version